# Generated by Django 4.2 on 2024-12-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=36, verbose_name='密码')),
                ('phone', models.CharField(max_length=50, verbose_name='电话')),
                ('avatar', models.CharField(max_length=255, verbose_name='头像')),
                ('sex', models.CharField(max_length=20, verbose_name='性别')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('status', models.BooleanField(verbose_name='封禁')),
                ('remarks', models.TextField(verbose_name='描述')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.role')),
            ],
        ),
    ]
