# Generated by Django 4.2 on 2024-12-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('foodname', models.CharField(max_length=50, verbose_name='食物名称')),
                ('foodicon', models.CharField(max_length=100, verbose_name='食物图标')),
                ('foodprocedure', models.TextField(verbose_name='做菜步骤')),
                ('video', models.CharField(max_length=100, verbose_name='视频')),
                ('price', models.FloatField(verbose_name='价格')),
                ('remarks', models.TextField(verbose_name='描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
