# Generated by Django 4.2 on 2024-12-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='food',
            table='sys_food',
        ),
    ]
