# Generated by Django 4.2 on 2024-12-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('user', models.CharField(max_length=50, verbose_name='用户信息')),
                ('food', models.CharField(max_length=50, verbose_name='食物信息')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('remarks', models.TextField(verbose_name='描述')),
            ],
        ),
    ]
